/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demoapp_jnibycmakedemo_HelloJNI */

#ifndef _Included_com_demoapp_jnibycmakedemo_HelloJNI
#define _Included_com_demoapp_jnibycmakedemo_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demoapp_jnibycmakedemo_HelloJNI
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demoapp_jnibycmakedemo_HelloJNI_printHello
  (JNIEnv *, jclass);

/*
 * Class:     com_demoapp_jnibycmakedemo_HelloJNI
 * Method:    printString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_demoapp_jnibycmakedemo_HelloJNI_printString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_demoapp_jnibycmakedemo_HelloJNI
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_demoapp_jnibycmakedemo_HelloJNI_getJniString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
